"""Pydantic schemas for API validation."""

from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    Token,
    TokenPayload,
    LoginRequest,
    PasswordChange,
    PasswordReset,
)
from app.schemas.unit import UnitCreate, UnitUpdate, UnitResponse
from app.schemas.beneficiary import (
    BeneficiaryCreate,
    BeneficiaryUpdate,
    BeneficiaryResponse,
    BeneficiaryListResponse,
    MedicalDataResponse,
    MedicalDataUpdate,
    ContactCreate,
    ContactUpdate,
    ContactResponse,
    RiskBehaviorCreate,
    RiskBehaviorUpdate,
    RiskBehaviorResponse,
)
from app.schemas.pai import PAICreate, PAIUpdate, PAIResponse
from app.schemas.objective import (
    ObjectiveCreate,
    ObjectiveUpdate,
    ObjectiveResponse,
    ObjectiveProgressUpdate,
    ObjectiveStatusUpdate,
    ActionCreate,
    ActionUpdate,
    ActionResponse,
    IndicatorCreate,
    IndicatorResponse,
)
from app.schemas.journal import (
    JournalEntryCreate,
    JournalEntryUpdate,
    JournalEntryResponse,
    JournalCategoryResponse,
)
from app.schemas.common import PaginatedResponse, Message

__all__ = [
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "PasswordChange",
    "PasswordReset",
    "UnitCreate",
    "UnitUpdate",
    "UnitResponse",
    "BeneficiaryCreate",
    "BeneficiaryUpdate",
    "BeneficiaryResponse",
    "BeneficiaryListResponse",
    "MedicalDataResponse",
    "MedicalDataUpdate",
    "ContactCreate",
    "ContactUpdate",
    "ContactResponse",
    "RiskBehaviorCreate",
    "RiskBehaviorUpdate",
    "RiskBehaviorResponse",
    "PAICreate",
    "PAIUpdate",
    "PAIResponse",
    "ObjectiveCreate",
    "ObjectiveUpdate",
    "ObjectiveResponse",
    "ObjectiveProgressUpdate",
    "ObjectiveStatusUpdate",
    "ActionCreate",
    "ActionUpdate",
    "ActionResponse",
    "IndicatorCreate",
    "IndicatorResponse",
    "JournalEntryCreate",
    "JournalEntryUpdate",
    "JournalEntryResponse",
    "JournalCategoryResponse",
    "PaginatedResponse",
    "Message",
]
